name: Install
description: Install dependencies for building and PHP
inputs:
  php-version:
    required: true
    description: "PHP version to use"
runs:
  using: composite
  steps:
    - name: Install PHP with extensions
      uses: shivammathur/setup-php@v2
      with:
        php-version: ${{ inputs.php-version }}
        ini-values: assert.exception=1, zend.assertions=1, error_reporting=-1, log_errors_max_len=0, display_errors=On, extension=pdo_tsurugi.so
        tools: none

    - name: apt
      shell: bash
      run: |
        sudo apt-get update
        sudo apt-get install -y \
          build-essential \
          autoconf \
          libtool \
          pkg-config \
          wget \
          cargo \
          protobuf-compiler
