name: Push

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - '**'

permissions:
  contents: read

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.url || github.run_id }}
  cancel-in-progress: true

jobs:
  Linux-64:
    name: Tests on Linux 64-bit

    runs-on: ubuntu-24.04

    strategy:
      fail-fast: false
      matrix:
        php-version:
          - '8.4'
          - '8.5'
    services:
      tsurugi-db:
        image: ghcr.io/project-tsurugi/tsurugidb:1.3.0
        ports:
          - 12345:12345

    steps:
      - name: git checkout
        uses: actions/checkout@v4

      - name: Install PHP with extensions
        uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ matrix.php-version }}
          ini-values: assert.exception=1, zend.assertions=1, error_reporting=-1, log_errors_max_len=0, display_errors=On, extension=pdo_tsurugi.so
          tools: none

      - name: apt
        run: |
          sudo apt-get update && \
          sudo apt-get install -y \
            build-essential \
            autoconf \
            libtool \
            pkg-config \
            wget \
            git \
            cargo \
            protobuf-compiler

      - name: Install cbindgen
        run: |
          wget http://launchpadlibrarian.net/751133175/cbindgen_0.27.0-1ubuntu1_amd64.deb && \
          sudo dpkg -i cbindgen_0.27.0-1ubuntu1_amd64.deb && \
          rm cbindgen_0.27.0-1ubuntu1_amd64.deb

      - name: Create cbindgen.toml
        run: |
          cat <<EOF > cbindgen.toml
            [enum]
            rename_variants = "QualifiedScreamingSnakeCase"
          EOF

      - name: Build tsubakuro
        run: |
          git clone --depth=1 https://github.com/project-tsurugi/tsubakuro-rust.git tsubakuro-rust && \
          cd tsubakuro-rust/tsubakuro-rust-ffi && \
          cargo build --release && \
          cbindgen --lang C --config "${GITHUB_WORKSPACE}/cbindgen.toml" --output tsubakuro-rust-ffi.h

      - name: Build and install package
        run: |
          cd src && \
          phpize && \
          ./configure --with-pdo_tsurugi="${GITHUB_WORKSPACE}/tsubakuro-rust" && \
          make -j$(nproc) && \
          sudo make install

      - name: Run tests
        run: |
          export PDO_TSURUGI_TEST_ENDPOINT=tcp://localhost:12345
          php src/run-tests.php tests \
            -g FAIL,BORK,LEAK,XLEAK \
            --no-progress \
            --offline \
            --show-diff \
            --show-slow 1000 \
            --set-timeout 120
