name: Push

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - '**'

permissions:
  contents: read

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.url || github.run_id }}
  cancel-in-progress: true

jobs:
  Linux-64:
    name: Tests on Linux 64-bit
    runs-on: ubuntu-24.04
    strategy:
      fail-fast: false
      matrix:
        php-version:
          - '8.4'
          - '8.5'
    services:
      tsurugi-db:
        image: ghcr.io/project-tsurugi/tsurugidb:1.3.0
        ports:
          - 12345:12345

    steps:
      - name: git checkout
        uses: actions/checkout@v4

      - name: Install dependencies
        uses: ./.github/actions/install
        with:
          php-version: ${{ matrix.php-version }}

      - name: Install cbindgen
        run: |
          wget http://launchpadlibrarian.net/751133175/cbindgen_0.27.0-1ubuntu1_amd64.deb && \
          sudo dpkg -i cbindgen_0.27.0-1ubuntu1_amd64.deb && \
          rm cbindgen_0.27.0-1ubuntu1_amd64.deb

      - name: Build
        uses: ./.github/actions/build

      - name: Run tests
        uses: ./.github/actions/tests
